version: '3.9'

services:
    express:
        container_name: express
        build: .
        env_file: .env
        ports:
            - '${EXPRESS_PORT}:${EXPRESS_PORT}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        ports:
            - '${MONGO_PORT}:27017'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
